# kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-0.32.0/deploy/static/provider/cloud/deploy.yaml

apiVersion: skaffold/v2beta4
kind: Config
deploy:
  kubectl:
    manifests:
      - ../infrastructure/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: pinkelgrg/app-authentication
      context: ../authentication
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    # - image: pinkelgrg/app-client
    #   context: ../client
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: "src/**/*.{ts,scss,tsx}"
    #         dest: .
